### ISSUE TITLE
Consider updating to simdjson 0.1.1

### ISSUE THREAD

**Issue by lemire** [luizperes/simdjson_nodejs#10]
We have a new version which has precomputed string lengths, and supporting strings with null characters in them.

**Comment by luizperes** [comment]
Hi @lemire, thanks for the update, will do it soon. Sorry for the delay in answering, I caught a bronchitis this week so I took it off.

**Comment by luizperes** [comment]
Hi @lemire, it has been done here: https://github.com/luizperes/simdjson_nodejs/pull/11
