### ISSUE TITLE
Very big JSON (up to 2gb)

### ISSUE THREAD

**Issue by hrdwdmrbl** [luizperes/simdjson_nodejs#13]
I'm working on a project which needs to parse some very large stringified JSON (up to 2GB).

It isn't clear to me whether this issue is the same as https://github.com/luizperes/simdjson_nodejs/issues/5 or not

**Comment by luizperes** [comment]
Hi @hrdwdmrbl, the problem with issue #5 is that there is some overhead in converting the C++ object into a JS object. I am working on that on branch `fix-5`

**Comment by luizperes** [comment]
Hi @hrdwdmrbl, I have fixed your problem by creating the `lazyParse` function. It is already merged with the `master` branch, please check its usage on the README file, I am also going to update the package on npm. I really appreciate your feedback.

Please close this issue if you feel this change is good enough, cheers!

**Comment by luizperes** [comment]
Closing this, as a solution was already done. Please reopen that if you need something else @hrdwdmrbl
