### ISSUE TITLE
Consider updating to simdjson 0.2.0

### ISSUE THREAD

**Issue by lemire** [luizperes/simdjson_nodejs#18]
The library simdjson has a new major release (0.2.0). Major changes:

* Support for 64-bit ARM processors, can run under iOS (iPhone).
* Runtime dispatching on x64 processors (switches to SSE on older x64 processors, uses AVX2 when available). Supports processors as far back as the Intel Westmere.
* More accurate number parsing.
* Fixes most warnings under Visual Studio.
* Several small bugs have been fixed.
* Better performance in some cases.
* Introduces a JSON Pointer interface https://tools.ietf.org/html/rfc6901
* Better and more specific error messages (with optional textual descriptions).
* valgrind clean.
* Unified code style (LLVM).

**Comment by luizperes** [comment]
Thanks for this update, @lemire, I was waiting for it!

**Comment by luizperes** [comment]
There a lot of breaking changes on this new version, so I think I will need some more time to do it, as I will have to touch the structure of the project

**Comment by luizperes** [comment]
Hi @lemire, I have updated and published on npm. Please let me know if you have any questions!
