### ISSUE TITLE
Reporting timings in GB/s

### ISSUE THREAD

**Issue by lemire** [luizperes/simdjson_nodejs#21]
It would be more interesting if we could report the timings (in the README.md) in GB/s, or some other normalized metric.

**Comment by dalisoft** [comment]
Maybe in `HPS (Handle-per Second)` or `PPS (Parse-per-Second)`?

**Comment by luizperes** [comment]
@dalisoft  The original repo already does GB/s. Also it's how we usually evaluate streaming/text processing on papers, that is why he mentions GB/s.

**Comment by dalisoft** [comment]
Would be nice to see benchmark, i know only Request/sec or calls per second. About GB/sec i see, but never realized in benchmarks

**Comment by lemire** [comment]
You have to define the payload for requests per second to be meaningful. Parsing an empty JSON document can be done an infinite number of times per second.

**Comment by dalisoft** [comment]
@lemire Yes, i understand.
3-4 types of JSON payloads.

1. `{ "status": "success" }` - One-line simple responses
2. `{ "status": "success", "data": { "id": "uuiv4", ...other_datas } }` - User-data or simple query responses (max 1Kb)
3. `{ ...type2, "ref": { ...$ref_data, ...data_too_here } }` - Structured data of users with their references (~3-4K)
4. Large payload - Basically more than 10KB

I can benchmark with these type of datas if necessary

**Comment by lemire** [comment]
@dalisoft 

If the document is small enough, we reach millions of documents parsed per second. This was tested upstream. Our benchmarking tools now report the number of documents parsed per second.

**Comment by luizperes** [comment]
PR #33 closes this issue
