### ISSUE TITLE
Update bindings to simdjson 0.3

### ISSUE THREAD

**Issue by luizperes** [luizperes/simdjson_nodejs#24]
Once `simdjson` is updated to its version 0.3, we no longer will need to pass flags such as the -mavx2. That will fix issues #3 and #23

**Comment by lemire** [comment]
cc @jkeiser

**Comment by luizperes** [comment]
I have checked #6 and I think it will fix it too.

**Comment by luizperes** [comment]
Closing this issue because:
- PR #27 fixes the issue with the flags. 
- Issue #25 is duplicate of this one.
