### ISSUE TITLE
Detect dynamically AVX2 within npm

### ISSUE THREAD

**Issue by lemire** [luizperes/simdjson_nodejs#3]
When can detect AVX2 dynamically within npm without user intervention, see for example...

https://github.com/SalvatorePreviti/roaring-node/blob/master/binding.gyp#L24-L29

**Comment by luizperes** [comment]
That sounds good! I am still to test these bindings in all three platforms (we got an error with windows https://github.com/luizperes/simdjson_nodejs/issues/1) and will totally add the AVX2 checking!

Thanks @lemire

**Comment by luizperes** [comment]
Hi @lemire, I think I fixed this issue. However, because I do not have a `AVX2` Linux machine, I would like to ask if you could download the branch `issue-6` (https://github.com/luizperes/simdjson_nodejs/tree/issue-6) and test if it is still compiling for Linux.

It was needed because we were having a bug where the bindings were only working for Linux (please see #1 and #6).

I would appreciate if you could give me an update on this issue. I will merge the code onto master when this issue has been fixed.

Thank you!

**Comment by lemire** [comment]
@luizperes I have just emailed to your sfu address instructions for how to access (by ssh/linux) Linux servers with AVX2.

Will that help?

**Comment by lemire** [comment]
(If you don't get my email, please reach out to me at lemire@gmail.com.)

**Comment by lemire** [comment]
Idea: it is 10x harder to support a platform you cannot directly access.

**Comment by luizperes** [comment]
@lemire That helps a lot, I received your email, will work on that and will update you here! Thanks!

**Comment by luizperes** [comment]
Hi @lemire, it is working properly on Linux as well, thanks for the help. Also, if you kept my user would be good, because I realized that the `Nan` Google V8, might actually be worse than the previous `Napi`, so I will need to cherry pick some of the commits before I merge it. Thank you again!

**Comment by lemire** [comment]
Sure. I also have other Linux machines if you want further testing.

@TkTech : I can give you the same access if you need it.

**Comment by TkTech** [comment]
@lemire thanks for the offer, I luckily have a large collection of random boxes from my osdev days. Did you see the new [POWER9 blackbird](https://raptorcs.com/content/BK1B01/intro.html)? First POWER9 I've seen around ~$1k for PCU+board.

@luizperes There is also the [Intel Software Development Emulator](https://software.intel.com/en-us/articles/intel-software-development-emulator) for win/mac/linux hosts. Will be slow as the dickens, but if you're just doing development and testing it's perfect for emulating AVX2/AVX-512 for a single process.

**Comment by lemire** [comment]
Anyhow, I am happy to provide access to our machines for this type of research.

Evidently, one can also get access to fun machines on cloud providers like Packet.

(Yes. I have a POWER9 machine. Was way more expensive than that... but now that I have it...)

**Comment by luizperes** [comment]
Thanks for the info about the emulator @TkTech !

**Comment by luizperes** [comment]
Hi @lemire, I am detecting AVX2 now on the (merged) branch https://github.com/luizperes/simdjson_nodejs/tree/proper-fix-issue-6. I've tested so far on Mac OS and Linux and it looks good. I am waiting for @davaloper to update me on Windows.

Other than that, please let me know if this issue can be closed. Cheers

**Comment by lemire** [comment]
Upstream, simdjson will provide runtime dispatch. So this should not be necessary in the future.

cc @ioioioio

**Comment by luizperes** [comment]
I have updated to `0.2.0`. Could you confirm that @lemire and @ioioioio?

**Comment by lemire** [comment]
@luizperes I think that your code still check for AVX2. You don't need that anymore. 

- On 64-bit ARM, no check should be necessary. We don't support 32-bit ARM.
- We don't support 32-bit x86... 
- We support x64 with a minimum of SSE 4.2 + CLMUL. This is what fairly old processors have (Westmere, Sandy Bridge...).

What you do (check for AVX2 and then bail out) should work fine if you not on ARM, but you could weaken quite a bit the checks.

**Comment by luizperes** [comment]
So, would it suffice if we said we don't support 32-bit at all?

I will likely use the same directives simdjon is using then, good to know, thanks!

**Comment by lemire** [comment]
Right... and to be prudent check for sse 4.2 and clmul on x64.

**Comment by luizperes** [comment]
I just realized I did not update that (with #23). Hi @lemire, is it correct that we don't need to use the flags `-mavx2` anymore?

**Comment by lemire** [comment]
Please be advise that we no longer require SSE 4.2. The upcoming version of simdjson will run *everywhere*.

**Comment by lemire** [comment]
@luizperes You should update to version 0.3 in a few days. You will just compile without any flag. It will run everywhere.

**Comment by luizperes** [comment]
PR #27 fixes this issue
