### ISSUE TITLE
Update mocha to a version > 7.1.1

### ISSUE THREAD

**Issue by luizperes** [luizperes/simdjson_nodejs#32]
**Problem**
Mocha `7.1.0` is using an outdated version of `mkdirp` and that is causing a warning of `low severity vulnerability`. Updating mocha to `7.1.1` (the latest at the moment on `npm`) is no good as well, as it is using `mkdirp@0.5.3` and we get a deprecated message: `Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)`. 

**Solution**
We will have to wait for mocha to update its version so to fix that deprecated warning.

<img width="1011" alt="Screen Shot 2020-04-08 at 1 57 39 AM" src="https://user-images.githubusercontent.com/6173065/78765168-7966cb80-793c-11ea-83f4-25b61ed616e4.png">

CC @nojvek

**Comment by nojvek** [comment]
Iwe only use mocha in dev env (I.e building the module). After its published, mocha shouldn’t be needed so this should be okay. 

But you’re right. Mocha should update themselves to be warning free.

**Comment by luizperes** [comment]
Fixed on #39
