### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Uzlopak** [luizperes/simdjson_nodejs#59]
Well. Is it?

**Comment by luizperes** [comment]
HI @Uzlopak, I missed your messages as I was busy with my work and masters. I will try to update this repo soon.

**Comment by Uzlopak** [comment]
I can reactivate the PRs if you like...

**Comment by Uzlopak** [comment]
I restored the branches, of my PRs (where i deleted them). So you can open the PRs again if you like and merge them
